version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - restore_cache:
          key: pom-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: pom-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_artifacts:
          path: target/ATLauncher-*.exe

      - store_artifacts:
          path: target/ATLauncher-*.jar

      - store_artifacts:
          path: target/ATLauncher-*.zip
