version: 2
workflows:
  version: 2
  build_test_package:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
jobs:
  build:
    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - restore_cache:
          key: pom-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: pom-{{ checksum "pom.xml" }}
  test:
    docker:
      - image: circleci/openjdk:8

    steps:
      - run: mvn test
  package:
    docker:
      - image: circleci/openjdk:8

    steps:
      - run: mvn package

      - store_artifacts:
          path: target/ATLauncher-*.exe

      - store_artifacts:
          path: target/ATLauncher-*.jar

      - store_artifacts:
          path: target/ATLauncher-*.zip
