name: getMemory

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup and install Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install memory dependency
        run: go get github.com/pbnjay/memory
        working-directory: getMemory

      - name: Build artifacts
        run: |
          GOOS=windows GOARCH=386 go build -o dist/getMemory.exe getMemory.go
          GOOS=linux GOARCH=386 go build -o dist/getMemory-linux getMemory.go
          GOOS=darwin GOARCH=386 go build -o dist/getMemory-osx getMemory.go
          GOOS=windows GOARCH=amd64 go build -o dist/getMemory-x64.exe getMemory.go
          GOOS=linux GOARCH=amd64 go build -o dist/getMemory-x64-linux getMemory.go
          GOOS=darwin GOARCH=amd64 go build -o dist/getMemory-x64-osx getMemory.go
        working-directory: getMemory

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: getMemory
          path: getMemory/dist/*
